---
title: "...треба..."
subtitle: "Разом зможемо!"
logo: "logo.png"

header: false
footer: '<p>Створив <span class="has-text-danger">❤️</span> <a href="httpss://github.com/WalkxCode">Володимир Коваленко</a> </p>'

stylesheet:
  - "assets/custom.css"

columns: "3"
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "../assets/wallpaper.png"

  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "../assets/wallpaper.png"

services:
  - name: "Сервіси"
    icon: ""
    items:
      - name: "Obsidian"
        logo: "assets/services/obsidian.png"
        subtitle: "obsidian.m-e.pp.ua"
        url: "https://obsidian.m-e.pp.ua"
        target: "_blank"
      - name: "Portainer-RPI3"
        logo: "assets/services/port.png"
        subtitle: "portainer.m-e.pp.ua"
        url: "https://portainer.m-e.pp.ua"
        target: "_blank"
      - name: "Portainer-ORPI"
        logo: "assets/services/port.png"
        subtitle: "portainer1.m-e.pp.ua"
        url: "https://lib.m-e.pp.ua"
        target: "_blank"
      - name: "Portainer-X64"
        logo: "assets/services/port.png"
        subtitle: "portainer2.m-e.pp.ua"
        url: "https://portainer2.m-e.pp.ua"
        target: "_blank"
      - name: "Budibase"
        logo: "assets/services/bb.png"
        subtitle: "bb.m-e.pp.ua"
        url: "https://bb.m-e.pp.ua"
        target: "_blank"
      - name: "Media"
        logo: "assets/services/media.png"
        subtitle: "media.m-e.pp.ua"
        url: "https://media.m-e.pp.ua"
        target: "_blank"
      - name: "flowise.m-e.pp.ua"
        logo: "assets/services/flowise.png"
        subtitle: "Flowise"
        url: "https://flowise.m-e.pp.ua"
        target: "_blank"
      - name: "Synapse-admin"
        logo: "assets/services/admin.png"
        subtitle: "admin.m-e.pp.ua"
        url: "https://admin.m-e.pp.ua"
        target: "_blank"
      - name: "NGNX-застосунки"
        logo: "assets/services/ngnx.png"
        subtitle: "ngnx.m-e.pp.ua"
        url: "https://ngnx.m-e.pp.ua"
        target: "_blank"
      - name: "Perlite"
        logo: "assets/services/perlite.png"
        subtitle: "perlite.m-e.pp.ua"
        url: "https://perlite.m-e.pp.ua"
        target: "_blank"
      - name: "TypeBot-редактор"
        logo: "assets/services/typebot1.png"
        subtitle: "typebot-b.m-e.pp.ua"
        url: "https://typebot-b.m-e.pp.ua"
        target: "_blank"
      - name: "TypeBot-готові"
        logo: "assets/services/typebot.png"
        subtitle: "typebot-v.m-e.pp.ua"
        url: "https://typebot-v.m-e.pp.ua"
        target: "_blank"
      - name: "GPT4free"
        logo: "assets/services/gpt.png"
        subtitle: "gpt.m-e.pp.ua"
        url: "https://gpt.m-e.pp.ua"
        target: "_blank"
      - name: "Nginx-proxy"
        logo: "assets/services/dns.png"
        subtitle: "dns.m-e.pp.ua"
        url: "https://dns.m-e.pp.ua"
        target: "_blank"
      - name: "Element"
        logo: "assets/services/element.png"
        subtitle: "element.m-e.pp.ua"
        url: "https://element.m-e.pp.ua"
        target: "_blank"
      - name: "Matrix"
        logo: "assets/services/matrix.png"
        subtitle: "matrix.m-e.pp.ua"
        url: "https://matrix.m-e.pp.ua"
        target: "_blank"
      - name: "...треба..."
        logo: "assets/services/treba.png"
        subtitle: "treba.m-e.pp.ua"
        url: "https://treba.m-e.pp.ua"
        target: "_blank"
      - name: "NodeRed"
        logo: "assets/services/red.png"
        subtitle: "red.m-e.pp.ua"
        url: "https://red.m-e.pp.ua"
        target: "_blank"
      - name: "Читальня"
        logo: "assets/services/lib.png"
        subtitle: "lib.m-e.pp.ua"
        url: "https://lib.m-e.pp.ua"
        target: "_blank"
      - name: "Редактор Drakonhub"
        logo: "assets/services/drn.png"
        subtitle: "Drakonhub"
        url: "https://yh.m-e.pp.ua"
        target: "_blank"

weather:
  enabled: false
  api_key: ""
  lat: ""
  lon: ""
  units: "metric"
  lang: "en"

search:
  enabled: false
  url: ""

monitoring:
  enabled: false
  api_key: ""

translations:
  en:
    weather: "Weather"
    search: "Search"

  uk:
    weather: "Погода"
    search: "Пошук"